#!/bin/bash  
#Setting python virtual environmen:
#if needed uncomment
#python3 -m venv pEnvironment-env
#source pEnvironment-env/bin/activate

echo "FIX NanoShaper executable and shared library for C functions"
read -p "Continue? (enter)"
echo "Linking NanoShaper executable"
	# Getting patchelf
	#cd patchelf
	#./bootstrap.sh
	#./configure --prefix="$HOME/.local"
	#make install
	#strip --strip-unneeded ~/.local/bin/patchelf
	#gzip -9 ~/.local/share/man/man1/patchelf.1
	#cd -
	## setting NS libraries
lib_absPATH=$(readlink -f NS_lib)
patchelf --set-rpath $lib_absPATH/ NanoShaper
patchelf --set-interpreter $lib_absPATH/ld-linux-x86-64.so.2 NanoShaper
patchelf --add-needed librt.so.1 NanoShaper
patchelf --add-needed libpthread.so.0 NanoShaper
echo "Fixng ownership"
chmod +x NanoShaper
chmod +x NS_lib/*
sleep 1
echo "copying NanoShaper executable to source folder"
cp NanoShaper ../siteFerret/refExecutable/
cp ../confFiles/surfaceConfiguration.prm ../siteFerret/refExecutable/
echo "Creating shared C library"
gcc -fPIC -c Cfunc.c -lm || gcc -fPIC -c Cfunc.c -lm -std=c99
gcc -shared Cfunc.o -o libCfunc.so
echo "copying libCfunc.so to source folder"
cp libCfunc.so ../siteFerret/


